"""empty message

Revision ID: 127bd32e101c
Revises: 2a8915925b03
Create Date: 2022-08-19 11:27:27.584666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127bd32e101c'
down_revision = '2a8915925b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'seeking_venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venues', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
